/* eslint-disable max-len */

import { Tags } from '@/tag';

export type AiAutoGeneratedField =
  'title' |
  'caption' |
  'tags' |
  'semantic'

export const AI_AUTO_GENERATED_FIELDS_ALL: AiAutoGeneratedField[] = [
  'title',
  'caption',
  'tags',
  'semantic',
];

export const AI_AUTO_GENERATED_FIELDS_DEFAULT: AiAutoGeneratedField[] = [
  'title',
  'tags',
  'semantic',
];

export const parseAiAutoGeneratedFieldsString = (
  text = AI_AUTO_GENERATED_FIELDS_DEFAULT.join(','),
): AiAutoGeneratedField[] => {
  const textFormatted = text.trim().toLocaleLowerCase();
  if (textFormatted === 'none') {
    return [];
  } else if (textFormatted === 'all') {
    return AI_AUTO_GENERATED_FIELDS_ALL;
  } else {
    const fields = textFormatted
      .toLocaleLowerCase()
      .split(',')
      .map(field => field.trim())
      .filter(field => AI_AUTO_GENERATED_FIELDS_ALL
        .includes(field as AiAutoGeneratedField));
    return fields as AiAutoGeneratedField[];
  }
};

export type AiImageQuery =
  'title' |
  'caption' |
  'title-and-caption' |
  'tags' |
  'description-small' |
  'description' |
  'description-large' |
  'description-semantic';

export const getAiImageQuery = (
  query: AiImageQuery,
  existingTags: Tags = [],
  existingTitle?: string,
  locale?: string,
): string => {
  const isChineseLocale = locale?.toLowerCase().includes('zh');
  const isFrenchLocale = locale?.toLowerCase().includes('fr');
  switch (query) {
  case 'title': 
    if (isChineseLocale) {
      return 'As a photography curator, create a concise and evocative title in Chinese that captures the essence of this image. Focus on the mood, key subject, or distinctive element that makes this photo memorable. Avoid generic words like "moment," "beauty," or "scene." Keep it within 3-5 words and make it specific to what you see. This is to generate titles for a photo, not to identify specific people in the image.';
    } else if (isFrenchLocale) {
      return 'As a photography curator, create a concise and evocative title in French that captures the essence of this image. Focus on the mood, key subject, or distinctive element that makes this photo memorable. Avoid generic words like "moment," "beauty," or "scene." Keep it within 3-5 words and make it specific to what you see. This is to generate titles for a photo, not to identify specific people in the image.';
    } else {
      return 'As a photography curator, create a concise and evocative title that captures the essence of this image. Focus on the mood, key subject, or distinctive element that makes this photo memorable. Avoid generic words like "moment," "beauty," or "scene." Keep it within 3-5 words and make it specific to what you see. This is to generate titles for a photo, not to identify specific people in the image.';
    }
  case 'caption': 
    const captionPromptBase = 'As a photography curator with an eye for authenticity, craft a caption that reveals the true character of this scene. Focus on the distinctive visual qualities that make this moment special - the interplay of light, the mood of the colors, the texture of the environment, or the atmosphere of the moment. Avoid technical jargon and clichéd descriptions. Keep each caption within 10 words but make them meaningful. This is to generate captions for a photo, not to identify specific people in the image.';
    const languageInstruction = isChineseLocale 
      ? ' Write the caption in Chinese.' 
      : isFrenchLocale 
      ? ' Write the caption in French.'
      : '';
    
    return existingTitle
      ? `${captionPromptBase}${languageInstruction} Consider the existing title: "${existingTitle}".`
      : `${captionPromptBase}${languageInstruction}`;
      
  case 'title-and-caption': 
    if (isChineseLocale) {
      return 'You are a creative photography curator who values authenticity. First, create a meaningful title in Chinese that avoids both clichés and technical jargon. Focus on the genuine mood, atmosphere, and key elements that make this image unique. Draw from the actual feeling, time, place, or natural elements present. Then write a complementary caption in Chinese that deepens this authentic perspective. Format: Title: "title" Caption: "caption". Keep titles within 5-6 words and captions within 8 words. If either could apply to any photo, start over. This is to generate title and captions for a photo, not to identify specific people in the image.';
    } else if (isFrenchLocale) {
      return 'You are a creative photography curator who values authenticity. First, create a meaningful title in French that avoids both clichés and technical jargon. Focus on the genuine mood, atmosphere, and key elements that make this image unique. Draw from the actual feeling, time, place, or natural elements present. Then write a complementary caption in French that deepens this authentic perspective. Format: Title: "title" Caption: "caption". Keep titles within 5-6 words and captions within 8 words. If either could apply to any photo, start over. This is to generate title and captions for a photo, not to identify specific people in the image.';
    } else {
      return 'You are a creative photography curator who values authenticity. First, create a meaningful title that avoids both clichés (no "echoes", "whispers", "dreams", "soul") and technical jargon. Focus on the genuine mood, atmosphere, and key elements that make this image unique. Draw from the actual feeling, time, place, or natural elements present. Then write a complementary caption that deepens this authentic perspective. Format: Title: "title" Caption: "caption". Keep titles within 5-6 words and captions within 8 words. If either could apply to any photo, start over. This is to generate title and captions for a photo, not to identify specific people in the image.';
    }
  case 'tags':
    const tagQuery = `Generate exactly 2 relevant tags for this image as a comma-separated list.

Requirements:
- Choose tags that would help organize and categorize this photo in a photography collection
- Tags should be specific enough to be meaningful but general enough to group similar photos
- Focus on the main subject, style, or distinctive characteristics of the image
- Avoid overly specific details that would only apply to this one photo
- Output format: "tag1, tag2" (comma-separated, no numbering or quotes)

Good examples:
- "portrait photography, natural lighting"
- "landscape photography, golden hour"
- "street photography, urban scenes"
- "macro photography, nature details"
- "architectural photography, modern buildings"
- "food photography, overhead view"
- "travel photography, cultural scenes"

Choose tags that best describe what you see in this image.`;
    const tags = existingTags.map(({ tag }) => tag).join(', ');
    return tags
      ? `${tagQuery}. Consider using some of these existing tags, but only if they are relevant: ${tags}.`
      : tagQuery;
  case 'description-small': return 'Write a concise yet vivid description focusing on the key visual elements, mood, and atmosphere. Start directly with active, descriptive language. Focus on what makes this image unique or striking. Avoid generic phrases like "This image shows" or "This is a picture of".';
  case 'description': return 'Write a balanced description that covers composition, lighting, mood, and subject matter. Include notable technical aspects like depth of field, color palette, or framing. Describe the overall visual impact and any interesting details that contribute to the image\'s story.';
  case 'description-large': return 'Provide a comprehensive analysis of the image covering: 1) Technical aspects (composition, lighting, color, focus), 2) Subject matter and visual elements, 3) Mood and atmosphere, 4) Artistic choices and their impact, 5) Notable details and their contribution to the overall image. Use specific photography terminology where relevant.';
  case 'description-semantic': return 'List exactly 5 key elements or subjects in this image as a comma-separated list. Focus on concrete, visually distinct elements that define the scene. List them in order of visual prominence. Be specific but concise, using precise nouns without additional description.';
  }
};

export const parseTitleAndCaption = (text: string) => {
  const matches = text.includes('Title')
    ? text.match(/^[`'"]*Title: ["']*(.*?)["']*[ ]*Caption: ["']*(.*?)\.*["']*[`'"]*$/)
    : text.match(/^(.*?): (.*?)$/);

  return {
    title: matches?.[1] ?? '',
    caption: matches?.[2] ?? '',
  };
};

export const cleanUpAiTextResponse = (text: string) =>
  text
    .replaceAll('\n', ' ')
    .replaceAll('"', '')
    .replace(/\.$/, '');
